title = "Let's build a ... Docs"
languageCode = "en-us"
defaultContentLanguage = "en"
timeZone = "America/Chicago"
copyright = "© 2022-present, Let's build a ..."

theme = "PaperMod"

baseURL = 'https://docs.letsbuilda.dev/'
enableRobotsTXT = true
paginate = 15

disableKinds = ["taxonomyTerm"]

[params]
description = "Let's build A ... Docs"
defaultTheme = "auto"
showReadingTime = true
showCodeCopyButtons = true
showPostNavLinks = true
env = "development"
keywords = ["oss", "foss"]

[params.assets]
disableFingerprinting = true

# Shown on the home page
socialIcons = [
    { name = "github", url = "https://github.com/letsbuilda/" },
]

# Configure the home page
[params.profileMode]
enabled = true
title = "Let's build a ... "
subtitle = "Contributing made easy"
imageUrl = "/profile-image.png"
